/* global document */
import assert from 'node:assert/strict'
import {execFile} from 'node:child_process'
import {promisify} from 'node:util'
import fs from 'node:fs/promises'
import path from 'node:path'
import {child,ownedPath,noLinks} from './scope.mjs'
import {recordPart} from './report.mjs'
import {sha256,verifyByteTree} from './byte-tree.mjs'
import {regularFile} from './fixtures.mjs'
import {releasedResources} from './resources.mjs'
const exec=promisify(execFile)
const formats=['zip','tar','tar.gz','tar.bz2','tar.xz','tar.zst','7z','rar','txt.gz','txt.bz2','txt.xz','txt.zst']
const localParts=[...formats.map(f=>`format-${f}`),'compress-cancel','zip-password-wrong-correct','password-cancel','output-conflict','corrupt-partial-batch','malicious-zip','malicious-tar']
const payload=Buffer.from('generated archive payload\n')
const expected=new Map([['spaced file.txt',payload],['nested',null],['nested/second.txt',payload]])
export const archivesManifest=plan=>{assert.ok(plan.targets.every(t=>['local','cloud'].includes(t.kind)));return [{id:'desktop-archives-local',name:'Generated local archive formats and failure paths',providers:['local'],partIds:localParts},...(plan.targets.some(t=>t.kind==='cloud')?[{id:'desktop-archives-cloud',name:'Real cloud archive staging and round trip',providers:['local','cloud'],partIds:['compress-extract','collision-preserves-original','retained-staging']}]:[])]}
async function button(ui,text){await(await ui.browser.$(`//*[@role="dialog"]//button[normalize-space(.)="${text}"]`)).click()}
async function toast(ui,pattern,timeout=60_000){let text;await ui.browser.waitUntil(async()=>{text=await ui.browser.execute(()=>document.querySelector('.toast[role="status"]')?.textContent.trim()??'');return pattern.test(text)||/^Failed to extract:/.test(text)},{timeout,interval:100,timeoutMsg:'Archive completion feedback did not arrive'});assert.match(text,pattern);await ui.browser.waitUntil(async()=>!await ui.browser.execute(()=>document.querySelector('.toast[role="status"]')?.getClientRects().length),{timeout:20_000,interval:100});await ui.idle();return text}
function destination(fixture,text){const raw=text.replace(/^Extracted to /,'').replace(/ \(skipped .*\)$/,'');ownedPath(fixture.roots,raw);return raw}
async function extract(ui,raw){await ui.select(raw);await ui.menuAction('extract',raw)}
async function compress(ui,paths,name,password){await ui.select(paths[0]);for(const raw of paths.slice(1))await ui.modifiedSelect(raw,'Control');await ui.menuAction('compress',paths[0]);await(await ui.browser.$('#compress-archive-name')).waitForDisplayed({timeout:5000});await ui.fill(await ui.browser.$('#compress-archive-name'),name);if(password){await(await ui.browser.$('//*[@role="dialog"]//label[contains(.,"Protect with password")]')).click();const fields=await ui.browser.$$('[role="dialog"] input[type="password"]');assert.equal(fields.length,2);for(const field of fields)await ui.fill(field,password)}await button(ui,'Create')}
async function verifyInputs(fixture,inputs){const result=[];for(const [raw,bytes]of inputs){assert.deepEqual(await fixture.readBytes(raw),bytes);result.push({name:raw.split('/').at(-1),bytes:bytes.length,sha256:sha256(bytes)})}return result}
export async function archives(plan,fixture,ui,record){
  let generated,encryptedBytes
  const local=plan.targets.find(t=>t.kind==='local')
  await record('Generated local archive formats and failure paths',async result=>{
    result.phase='setup';const generatedResult=await exec('/usr/bin/python3',[path.join(ui.desktop.repo,'tests/support/native_fixture_archives.py')],{env:fixture.env,cwd:local.files,timeout:30_000,maxBuffer:512*1024});generated=Object.fromEntries(Object.entries(JSON.parse(generatedResult.stdout)).map(([key,value])=>[key,Buffer.from(value,'base64')]));assert.equal(Object.keys(generated).length,15);const base=child(local.files,'archives');await fixture.mkdir(base);const inputs=new Map()
    for(const format of formats)await recordPart(result,`format-${format}`,async part=>{
      result.phase='setup';const dir=child(base,`format-${format.replaceAll('.','-')}`);await fixture.mkdir(dir);const raw=child(dir,`roundtrip.${format}`);await fixture.write(raw,generated[format]);inputs.set(raw,generated[format]);await ui.navigate(dir);await ui.setView('list');result.phase='ui';part.ui='STARTED';await extract(ui,raw);part.feedback=await toast(ui,/^Extracted to /);const out=destination(fixture,part.feedback);result.phase='verification';if(format.startsWith('txt.'))assert.deepEqual(await fixture.readBytes(out),payload);else part.tree=await verifyByteTree(fixture,out,format==='rar'?new Map([['spaced file.txt',payload]]):expected);assert.deepEqual(await fixture.readBytes(raw),generated[format]);part.ui='ACKNOWLEDGED';part.verification='INDEPENDENT_MATCH'
    })
    const protectedDir=child(base,'protected'),source=child(protectedDir,'spaced source.txt'),zip=child(protectedDir,'secret.zip');await fixture.mkdir(protectedDir);await fixture.write(source,payload);inputs.set(source,payload);await ui.navigate(protectedDir)
    await recordPart(result,'compress-cancel',async part=>{result.phase='ui';await ui.select(source);await ui.menuAction('compress',source);await(await ui.browser.$('#compress-archive-name')).waitForDisplayed({timeout:5000});await ui.fill(await ui.browser.$('#compress-archive-name'),'cancelled');await button(ui,'Cancel');await ui.idle();result.phase='verification';assert.ok(!await fixture.exists(child(protectedDir,'cancelled.zip')));assert.deepEqual(await fixture.readBytes(source),payload);part.ui='ACKNOWLEDGED';part.verification='INDEPENDENT_MATCH'})
    await recordPart(result,'zip-password-wrong-correct',async part=>{
      result.phase='ui';await compress(ui,[source],'secret','generated-secret');part.creation=await toast(ui,/^Created /);encryptedBytes=await fixture.readBytes(zip);inputs.set(zip,encryptedBytes);await extract(ui,zip);const field=await ui.browser.$('#extract-password');await field.waitForDisplayed({timeout:60_000});await ui.fill(field,'incorrect-generated-secret');await button(ui,'Extract');await ui.browser.waitUntil(async()=>{const error=await ui.browser.$('[role="dialog"] .pill.error');return await error.isDisplayed()&&/incorrect|invalid|wrong/i.test(await error.getText())},{timeout:60_000,interval:100,timeoutMsg:'Wrong password did not return an actionable password dialog'});part.wrongPassword=await(await ui.browser.$('[role="dialog"] .pill.error')).getText();assert.equal(await(await ui.browser.$('#extract-password')).getValue(),'');await ui.fill(await ui.browser.$('#extract-password'),'generated-secret');await button(ui,'Extract');part.feedback=await toast(ui,/^Extracted to /);result.phase='verification';part.tree=await verifyByteTree(fixture,destination(fixture,part.feedback),new Map([['spaced source.txt',payload]]));assert.deepEqual(await fixture.readBytes(source),payload);part.ui='ACKNOWLEDGED';part.verification='INDEPENDENT_MATCH'
    })
    await recordPart(result,'password-cancel',async part=>{result.phase='setup';const before=(await fixture.snapshot(protectedDir)).map(e=>e.name).sort();result.phase='ui';await extract(ui,zip);await(await ui.browser.$('#extract-password')).waitForDisplayed({timeout:60_000});await button(ui,'Cancel extraction');part.feedback=await toast(ui,/^Extraction cancelled$/);result.phase='verification';assert.deepEqual((await fixture.snapshot(protectedDir)).map(e=>e.name).sort(),before);part.ui='ACKNOWLEDGED';part.verification='INDEPENDENT_MATCH'})
    await recordPart(result,'output-conflict',async part=>{result.phase='setup';const dir=child(base,'conflicts');await fixture.mkdir(dir);const raw=child(dir,'same.zip'),existing=child(dir,'same');await fixture.write(raw,generated.zip);inputs.set(raw,generated.zip);await fixture.mkdir(existing);await fixture.write(child(existing,'sentinel.txt'),'preserve\n');await ui.navigate(dir);result.phase='ui';await extract(ui,raw);part.feedback=await toast(ui,/^Extracted to /);const out=destination(fixture,part.feedback);assert.notEqual(out,existing);result.phase='verification';part.tree=await verifyByteTree(fixture,out,expected);await verifyByteTree(fixture,existing,new Map([['sentinel.txt',Buffer.from('preserve\n')]]));part.ui='ACKNOWLEDGED';part.verification='INDEPENDENT_MATCH'})
    await recordPart(result,'corrupt-partial-batch',async part=>{result.phase='setup';const dir=child(base,'partial');await fixture.mkdir(dir);const good=child(dir,'good.zip'),bad=child(dir,'broken.zip');await fixture.write(good,generated.zip);await fixture.write(bad,generated['broken.zip']);inputs.set(good,generated.zip);inputs.set(bad,generated['broken.zip']);await ui.navigate(dir);result.phase='ui';await ui.select(good);await ui.modifiedSelect(bad,'Control');await ui.menuAction('extract',good);part.feedback=await toast(ui,/^Extracted 1 archive, 1 failed\b/);assert.match(part.feedback,/broken.zip:/);result.phase='verification';part.tree=await verifyByteTree(fixture,child(dir,'good'),expected);assert.ok(!await fixture.exists(child(dir,'broken')));part.ui='ACKNOWLEDGED';part.verification='INDEPENDENT_MATCH'})
    for(const format of ['zip','tar'])await recordPart(result,`malicious-${format}`,async part=>{result.phase='setup';const dir=child(base,`malicious-${format}`);await fixture.mkdir(dir);const raw=child(dir,`hostile.${format}`),sentinel=child(dir,'sentinel.txt');await fixture.write(raw,generated[`malicious.${format}`]);inputs.set(raw,generated[`malicious.${format}`]);await fixture.write(sentinel,'preserve\n');await ui.navigate(dir);result.phase='ui';await extract(ui,raw);part.feedback=await toast(ui,/^Extracted to .*skipped /);result.phase='verification';part.tree=await verifyByteTree(fixture,destination(fixture,part.feedback),format==='zip'?new Map([...expected,['forbidden-native-archive.txt',payload]]):expected);assert.equal(await fixture.read(sentinel),'preserve\n');await assert.rejects(fs.lstat('/forbidden-native-archive.txt'),{code:'ENOENT'});part.ui='ACKNOWLEDGED';part.verification='INDEPENDENT_MATCH'})
    result.phase='verification';result.preservedInputs=await verifyInputs(fixture,inputs);result.resources=await releasedResources(ui,plan.runId)
  },{id:'desktop-archives-local',providers:['local']})
  const cloud=plan.targets.find(t=>t.kind==='cloud');if(!cloud)return
  await record('Real cloud archive staging and round trip',async result=>{
    ui.waitTimeout=180_000;const base=child(cloud.files,'archives'),source=child(base,'spaced source.txt'),zip=child(base,'cloud.zip');result.phase='setup';await fixture.mkdir(base);await fixture.write(source,payload);await ui.navigate(base)
    await recordPart(result,'compress-extract',async part=>{result.phase='ui';await compress(ui,[source],'cloud');part.creation=await toast(ui,/^Created /,600_000);const bytes=await fixture.readBytes(zip);assert.ok(bytes.length>payload.length);await extract(ui,zip);part.feedback=await toast(ui,/^Extracted to /,600_000);result.phase='verification';part.tree=await verifyByteTree(fixture,destination(fixture,part.feedback),new Map([['spaced source.txt',payload]]));assert.deepEqual(await fixture.readBytes(source),payload);assert.deepEqual(await fixture.readBytes(zip),bytes);part.archiveSha256=sha256(bytes);part.ui='ACKNOWLEDGED';part.verification='INDEPENDENT_MATCH'})
    await recordPart(result,'collision-preserves-original',async part=>{result.phase='setup';const before=await fixture.readBytes(zip);result.phase='ui';await compress(ui,[source],'cloud');const error=await ui.browser.$('[role="dialog"] .pill.error');await error.waitForDisplayed({timeout:600_000});part.feedback=await error.getText();assert.match(part.feedback,/already exists/i);await button(ui,'Cancel');await ui.idle();result.phase='verification';assert.deepEqual(await fixture.readBytes(zip),before);assert.deepEqual(await fixture.readBytes(source),payload);part.ui='ACKNOWLEDGED';part.verification='INDEPENDENT_MATCH'})
    await recordPart(result,'retained-staging',async part=>{result.phase='verification';const stage=path.join(local.run,'profile/data/browsey/cloud-workspaces');await noLinks(stage,fs);const dirs=await fs.readdir(stage);assert.equal(dirs.length,3);assert.equal(dirs.filter(n=>n.startsWith('compress-')).length,2);assert.equal(dirs.filter(n=>n.startsWith('extract-')).length,1);part.entries=[];let count=0;async function walk(raw,depth){assert.ok(depth<=4&&count++<32);await noLinks(raw,fs);const meta=await fs.lstat(raw);if(meta.isDirectory()){for(const name of await fs.readdir(raw))await walk(path.join(raw,name),depth+1)}else{const {bytes}=await regularFile(raw);part.entries.push({name:path.relative(stage,raw),bytes:bytes.length,sha256:sha256(bytes)})}}await walk(stage,0);assert.ok(part.entries.length>=4);result.resources=await releasedResources(ui,plan.runId);part.verification='INDEPENDENT_MATCH'})
  },{id:'desktop-archives-cloud',providers:['local','cloud']})
}
