/* global document */
import assert from 'node:assert/strict'
import {Key} from 'webdriverio'
import {child} from './scope.mjs'
import {verifyTree} from './editing.mjs'
import {recordPart} from './report.mjs'
import {beginPaste,waitActivityGone} from './progress.mjs'
import {heldProbe,assertCancelledOutput,transferListeners} from './cancellation.mjs'
import {recoveryEvidence} from './recovery.mjs'

export const interruptionManifest=plan=>{interruptionLocations(plan);return [{id:'interruption-local',name:'Owned process interruption and recovery startup',providers:['local'],
  partIds:['interrupted-overwrite','safe-startup','recovery-diagnostics']}]}
export function interruptionLocations(plan) {
  assert.deepEqual(plan.targets.map(t=>t.kind),['local'],'Process interruption must be local-only without provider subprocesses')
  const root=plan.targets[0].files,from=child(root,'interruption-source'),to=child(root,'interruption-target')
  return {id:'interruption-local',from,to,source:child(from,'body.txt'),target:child(to,'body.txt')}
}
export const interruptionProbes=plan=>{
  const p=interruptionLocations(plan)
  return [{id:p.id,source:p.source,target:p.target,holdPhase:'written',holdBytes:16384,holdMs:5000,slowMs:0}]
}
export async function interruption(plan,fixture,ui,record) {
  await record('Owned process interruption and recovery startup',async result=>{
    await ui.setView('list')
    const p=interruptionLocations(plan),content='interrupted new generated bytes\n'.padEnd(65536,'n'),original='protected old generated bytes\n'.padEnd(8192,'o'),
      source=new Map([['body.txt',content],['sentinel.txt','unrelated source\n']]),target=new Map([['body.txt',original],['sentinel.txt','unrelated target\n']])
    await recordPart(result,'interrupted-overwrite',async part=>{
      result.phase='setup';await fixture.mkdir(p.from);await fixture.mkdir(p.to)
      for(const [name,bytes] of source) await fixture.write(child(p.from,name),bytes)
      for(const [name,bytes] of target) await fixture.write(child(p.to,name),bytes)
      await ui.populateClipboard(p.from,[p.source],false,false)
      result.phase='ui';part.ui='STARTED';await beginPaste(ui,p.to,{conflict:'Overwrite'})
      part.checkpoint=await heldProbe(ui,plan.runId,p.id);assert.equal(part.checkpoint.observation.bytes,16384)
      const protection=await recoveryEvidence(plan,original)
      assert.equal(protection.originalCopies,1);assert.ok(protection.recoveryMarkers>0)
      await ui.interruptAndRestart();part.ui='INTERRUPTED_NO_COMPLETION_REPLY';part.signal='SIGKILL'
      result.phase='verification'
      const bytes=await fixture.read(p.target);assert.equal(bytes.length,16384);assertCancelledOutput(content,bytes);target.set('body.txt',bytes)
      await verifyTree(fixture,p.from,source);await verifyTree(fixture,p.to,target)
      part.recovery=await recoveryEvidence(plan,original);assert.equal(part.recovery.originalCopies,1)
      assert.equal(part.recovery.recoveryMarkers,protection.recoveryMarkers);part.verification='INDEPENDENT_MATCH'
    })
    await recordPart(result,'safe-startup',async part=>{
      result.phase='ui';part.ui='STARTED';await ui.navigate(p.to);await waitActivityGone(ui)
      const status=await ui.handshake(plan.runId)
      assert.equal(status.cancelTasks,0);assert.ok(status.probes.every(p=>!p.consumed),'Restart must not resume or replay the interrupted operation')
      assert.deepEqual(await transferListeners(ui),[])
      assert.equal(await ui.browser.execute(()=>document.querySelector('main.shell')?.getAttribute('data-operation-active')),'false')
      await ui.historyStep(false,{},true);await ui.historyStep(true,{},true)
      result.phase='verification';await verifyTree(fixture,p.from,source);await verifyTree(fixture,p.to,target)
      part.ui='ACKNOWLEDGED';part.verification='INDEPENDENT_MATCH';part.history='EMPTY_NEW_SESSION';part.resume='NOT_ATTEMPTED'
    })
    await recordPart(result,'recovery-diagnostics',async part=>{
      result.phase='ui';part.ui='STARTED';await ui.chord('s')
      const modal=await ui.browser.$('.settings-modal');await modal.waitForDisplayed({timeout:10_000})
      await ui.fill(await modal.$('input[placeholder="Filter settings"]'),'undo')
      const panel=await modal.$('.undo-storage');await panel.waitForDisplayed({timeout:10_000})
      await ui.browser.waitUntil(async()=>await panel.getAttribute('aria-busy')==='false'&&(await panel.getText()).includes('Last scan:'),{timeout:10_000})
      let text=await panel.getText();assert.match(text,/1 session with recovery markers/);assert.match(text,/session-only/)
      await (await panel.$('.//button[normalize-space(.)="Refresh backup information"]')).click()
      await ui.browser.waitUntil(async()=>await panel.getAttribute('aria-busy')==='false',{timeout:10_000})
      await (await panel.$('summary')).click();text=await panel.getText()
      assert.match(text,/does not restore, resume, delete backups, or clear markers/)
      assert.match(text,/without restoring undo history/)
      const expected=['profile','data','browsey','undo-sessions'].reduce(child,plan.targets[0].run)
      assert.equal(await (await panel.$('input[aria-label="Undo backup directory"]')).getValue(),expected)
      await ui.browser.keys([Key.Escape]);await modal.waitForExist({reverse:true,timeout:5000});await ui.idle()
      result.phase='verification';await verifyTree(fixture,p.from,source);await verifyTree(fixture,p.to,target)
      part.recovery=await recoveryEvidence(plan,original);assert.equal(part.recovery.originalCopies,1);assert.equal(part.recovery.recoveryMarkers,1)
      assert.equal((await ui.handshake(plan.runId)).cancelTasks,0);assert.deepEqual(await transferListeners(ui),[])
      part.ui='ACKNOWLEDGED';part.verification='INDEPENDENT_MATCH';part.diagnostics='REAL_READ_ONLY_SETTINGS_PANEL'
    })
  },{id:'interruption-local',providers:['local']})
}
