import assert from 'node:assert/strict'
import { test } from 'node:test'
import { listing, listingManifest, orderedFiles } from './listing.mjs'
import { makePlan, validateConfig, kinds, ownedPath } from './scope.mjs'
import { createReport, recordCase, finishReport, summarizeProviders } from './report.mjs'

const plan = makePlan(validateConfig({ schema: 1, targets: Object.fromEntries(kinds.map(kind =>
  [kind, kind === 'cloud' ? 'rclone://Generated/ai_agent_testfolder' : `/${kind}/ai_agent_testfolder`])),
rcloneConfig: '/local/ai_agent_testfolder/rclone.conf' }), '00000000-0000-4000-8000-000000000000')

// Independent orchestration model; these tests never count as native acceptance.
function model({ corrupt = false, failReset = false } = {}) {
  const roots = plan.targets.map(target => target.files)
  const items = new Map(roots.map(path => [path, null]))
  const observations = []
  const filters = new Map()
  let current, view = 'list', hidden = true, query = '', recursive = false, submitted = true
  let sortField = 'Name', direction = 'asc'
  const name = path => path.split('/').at(-1)
  const direct = raw => [...items.keys()].filter(path => path.slice(0, path.lastIndexOf('/')) === raw)
  const metadata = path => ({ path, name: name(path), kind: items.get(path) === null ? 'dir' : 'file',
    size: items.get(path)?.length ?? 0, modifiedMinute: 10 })
  const fixture = {
    mkdir: async raw => { ownedPath(roots, raw); assert.ok(!items.has(raw)); items.set(raw, null) },
    write: async (raw, bytes) => { ownedPath(roots, raw); assert.ok(!items.has(raw)); items.set(raw, bytes) },
    snapshot: async raw => direct(raw).map(metadata),
    read: async raw => corrupt ? 'corrupt generated bytes' : items.get(raw),
    exists: async raw => items.has(raw),
  }
  const accepted = path => {
    if (!hidden && name(path).startsWith('.')) return false
    if (query && !name(path).toLowerCase().includes(query.toLowerCase())) return false
    for (const [field, labels] of filters) {
      if (!labels.size) continue
      const label = field === 'Name' ? name(path).startsWith('.') ? 'Other symbols' : /^[a-f]/i.test(name(path)) ? 'A–F' : /^[m-r]/i.test(name(path)) ? 'M–R' : 'S–Z'
        : field === 'Type' ? items.get(path) === null ? 'dir' : name(path).split('.').at(-1).toLowerCase()
          : field === 'Size' ? items.get(path) === null ? 'directory' : items.get(path).length <= 10240 ? '0–10 KB' : '10–100 KB' : 'Today'
      if (!labels.has(label)) return false
    }
    return true
  }
  const compare = (a, b) => a < b ? -1 : a > b ? 1 : 0
  const key = path => sortField === 'Size' ? items.get(path)?.length ?? 0 : sortField === 'Modified' ? 10
    : sortField === 'Type' ? name(path).split('.').at(-1).toLowerCase() : name(path).toLowerCase()
  const ui = {
    navigate: async raw => { ownedPath(roots, raw); assert.equal(items.get(raw), null); current = raw },
    openFolder: async raw => { assert.equal(raw.slice(0, raw.lastIndexOf('/')), current); current = raw },
    breadcrumb: async raw => { assert.ok(current.startsWith(`${raw}/`)); current = raw },
    bookmarks: async () => {},
    setView: async next => { view = next },
    hidden: async next => { hidden = next },
    sort: async (field, next) => { sortField = field; direction = next },
    columnFilter: async (field, label, checked = true) => {
      if (!filters.has(field)) filters.set(field, new Set())
      if (checked) filters.get(field).add(label); else filters.get(field).delete(label)
    },
    resetColumn: async field => { if (failReset) throw new Error('synthetic reset failure'); filters.delete(field) },
    resetColumns: async () => { filters.clear() },
    filter: async (raw, seed, text) => { assert.equal(current, raw); assert.ok(direct(raw).includes(seed)); query = text; recursive = false },
    search: async (raw, text, enabled) => { assert.equal(current, raw); assert.equal(enabled, true); query = text; recursive = true; submitted = true },
    query: async (text, submit) => { query = text; if (recursive) submitted = submit },
    exitQuery: async raw => { assert.equal(current, raw); query = ''; recursive = false; submitted = true },
    listing: async (raw, expectedView, paths, { fileOrder } = {}) => {
      assert.equal(current, raw); assert.equal(view, expectedView)
      const actual = (recursive ? submitted ? [...items.keys()].filter(path => path.startsWith(`${raw}/`)) : [] : direct(raw)).filter(accepted)
      assert.deepEqual(actual.sort(), [...paths].sort())
      if (fileOrder) {
        const actualFiles = actual.filter(path => items.get(path) !== null)
          .sort((a, b) => (compare(key(a), key(b)) || compare(name(a).toLowerCase(), name(b).toLowerCase())) * (direction === 'desc' ? -1 : 1))
        assert.deepEqual(actualFiles, fileOrder)
      }
      observations.push({ raw, view, recursive, query, paths: [...paths] })
    },
  }
  return { fixture, ui, observations }
}

test('listing independently exercises sort/filter/reset/hidden/search transitions in both views on all five providers', async () => {
  const report = createReport(plan, kinds, listingManifest(plan))
  const { fixture, ui, observations } = model()
  await listing(plan, fixture, ui, (_name, action, metadata) => recordCase(report, metadata, action))
  finishReport(report); summarizeProviders(report)
  assert.equal(report.status, 'PASS')
  assert.ok(report.cases.every(item => item.parts.length === 15 && item.parts.every(part => part.status === 'PASS')))
  for (const target of plan.targets) {
    assert.equal(report.providers[target.kind].status, 'PASS')
    assert.equal(report.providers[target.kind].capabilities['scoped-recursive-search'].status, 'PASS')
    for (const view of ['list', 'grid']) assert.ok(observations.some(item => item.raw.startsWith(target.files) && item.view === view && item.recursive && item.paths.some(path => path.endsWith('/nested/Alpha-inner.TXT'))))
    assert.ok(observations.filter(item => item.recursive).every(item => item.paths.every(path => path.startsWith(`${item.raw}/`))))
  }
})

test('independent readback catches damaged generated files after acknowledged UI operations', async () => {
  const report = createReport(plan, kinds, listingManifest(plan))
  const { fixture, ui } = model({ corrupt: true })
  await assert.rejects(listing(plan, fixture, ui, (_name, action, metadata) => recordCase(report, metadata, action)), /fixture bytes/)
  assert.equal(report.cases[0].status, 'FAIL')
  assert.equal(report.cases[0].failureKind, 'RESULT_MISMATCH')
  assert.ok(report.cases.slice(1).every(item => item.status === 'NOT_RUN'))
})

test('reset failure stops once and preserves completed parts and other unrun provider cases', async () => {
  const report = createReport(plan, kinds, listingManifest(plan))
  const { fixture, ui } = model({ failReset: true })
  let attempts = 0
  const reset = ui.resetColumn
  ui.resetColumn = async field => { attempts++; await reset(field) }
  await assert.rejects(listing(plan, fixture, ui, (_name, action, metadata) => recordCase(report, metadata, action)), /reset failure/)
  assert.equal(attempts, 1)
  assert.deepEqual(report.cases[0].parts.map(part => part.status), [...Array(7).fill('PASS'), 'BLOCKED'])
  assert.ok(report.cases.slice(1).every(item => item.status === 'NOT_RUN'))
})

test('expected sort uses independent minutes, bytes, extensions and names with direction-aware ties', () => {
  const snapshot = [{ path: '/generated/b.TXT', name: 'b.TXT', kind: 'file', size: 2, modifiedMinute: 1 },
    { path: '/generated/A.md', name: 'A.md', kind: 'file', size: 1, modifiedMinute: 2 },
    { path: '/generated/.hidden', name: '.hidden', kind: 'file', size: 0, modifiedMinute: 0 }]
  assert.deepEqual(orderedFiles(snapshot, 'Modified', 'asc'), ['/generated/b.TXT', '/generated/A.md'])
  assert.deepEqual(orderedFiles(snapshot, 'Size', 'desc'), ['/generated/b.TXT', '/generated/A.md'])
  assert.deepEqual(orderedFiles(snapshot, 'Type', 'asc'), ['/generated/A.md', '/generated/b.TXT'])
  snapshot[1].modifiedMinute = 1
  assert.deepEqual(orderedFiles(snapshot, 'Modified', 'desc'), ['/generated/b.TXT', '/generated/A.md'])
})
