/* global document */
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
import path from 'node:path'
import {child,noLinks} from './scope.mjs'
import {recordPart} from './report.mjs'
import {regularFile} from './fixtures.mjs'
import {writePrivate,privateJson,processGone} from './privacy.mjs'
import {sha256,verifyByteTree} from './byte-tree.mjs'
import {releasedResources} from './resources.mjs'
const parts=['private-mime-proof','checked-cancel','unchecked-spaced-launch','failed-launch','checked-default-launch','default-cancel-preserves-association']
const initial='[Default Applications]\ntext/plain=generated-failure.desktop;\n\n[Added Associations]\ntext/plain=generated-success.desktop;generated-failure.desktop;\n'
const payload=Buffer.from('generated Open With fixture\n')
export const openWithManifest=plan=>{assert.deepEqual(plan.targets.map(t=>t.kind),['local']);return [{id:'desktop-open-with',name:'Private dummy Open With handlers and associations',providers:['local'],partIds:parts}]}
async function button(ui,text){await(await ui.browser.$(`//*[@role="dialog"]//button[normalize-space(.)="${text}"]`)).click()}
async function open(ui,raw){await ui.select(raw);await ui.menuAction('open-with',raw);await(await ui.browser.$('.open-with-modal')).waitForDisplayed({timeout:5000});await ui.browser.waitUntil(async()=>!await(await ui.browser.$('.open-with-modal')).getText().then(t=>t.includes('Loading apps…')),{timeout:30_000,interval:100});const names=await ui.browser.execute(()=>[...document.querySelectorAll('.open-with-modal .app-name')].map(n=>n.textContent.trim()));assert.deepEqual(names.slice(1).sort(),['Generated failed handler','Generated successful handler']);assert.equal(names.length,3);assert.ok(!await(await ui.browser.$('.open-with-modal .pill.error')).isExisting())}
async function pick(ui,success){await(await ui.browser.$(`//div[contains(@class,"open-with-modal")]//div[contains(@class,"apps")]//button[.//span[normalize-space(.)="Generated ${success?'successful':'failed'} handler"]]`)).click()}
async function checked(ui){const field=await ui.browser.$('.open-with-modal input[type="checkbox"]');return await field.isExisting()&&await field.isSelected()}
async function toggle(ui){await(await ui.browser.$('//div[contains(@class,"open-with-modal")]//label[contains(.,"Set as default")]')).click();assert.ok(await checked(ui))}
async function launches(log){try{return(await regularFile(log)).text.trim().split('\n').filter(Boolean).map(line=>JSON.parse(line))}catch(error){if(error.code==='ENOENT')return[];throw error}}
export async function openWith(plan,fixture,ui,record){
 await record('Private dummy Open With handlers and associations',async result=>{
  result.phase='setup';const local=plan.targets[0],profile=path.join(local.run,'profile'),data=path.join(profile,'data'),apps=path.join(data,'applications'),mime=path.join(profile,'config/mimeapps.list'),log=path.join(local.run,'artifacts/handler.jsonl'),base=child(local.files,'open-with'),raw=child(base,'spaced # name.txt');await fixture.mkdir(base);await fixture.write(raw,payload);await fs.mkdir(apps,{mode:0o700});const guard=await fs.readFile(path.join(ui.desktop.repo,'src/native_test/open_with.rs'),'utf8'),script=guard.match(/const HANDLER: &str = r###"([\s\S]*?)"###;/)?.[1];assert.ok(script);await writePrivate(path.join(data,'native_handler.py'),script,{exclusive:true});await writePrivate(path.join(data,'native-denied-handler'),'generated unavailable handler\n',{exclusive:true})
  for(const success of [true,false]){const name=`Generated ${success?'successful':'failed'} handler`,exec=success?`/usr/bin/python3 "${data}/native_handler.py" "${log}" %f`:`"${data}/native-denied-handler" %f`;await writePrivate(path.join(apps,`generated-${success?'success':'failure'}.desktop`),`[Desktop Entry]\nType=Application\nName=${name}\nExec=${exec}\nMimeType=text/plain;\nTerminal=false\n`,{exclusive:true})}await writePrivate(mime,initial,{exclusive:true});await ui.navigate(base);await ui.setView('list')
  const association=async()=>{await noLinks(mime,fs);return(await regularFile(mime)).text}
  const verifyLaunch=async(count)=>{let rows;await ui.browser.waitUntil(async()=>{rows=await launches(log);return rows.length>=count},{timeout:10_000,interval:100,timeoutMsg:'Actual generated handler did not record its argument'});assert.equal(rows.length,count);const row=rows.at(-1);assert.equal(row.parent,(await ui.handshake(plan.runId)).pid);assert.equal(row.executable,await fs.realpath('/usr/bin/python3'));assert.equal(row.path,raw);assert.equal(row.dataHome,data);assert.equal(row.display,':91');assert.equal(row.bytes,payload.length);assert.equal(row.sha256,sha256(payload));await ui.browser.waitUntil(()=>processGone(row.pid,row.start),{timeout:10_000,interval:100,timeoutMsg:'Generated handler did not exit'});return row}
  await recordPart(result,'private-mime-proof',async part=>{result.phase='verification';const proof=await privateJson(path.join(local.run,'artifacts/isolation.json'));for(const key of ['cookieRequired','privateBus','originNamespacesDifferent','personalConfigAbsent'])assert.equal(proof[key],true);assert.equal(proof.runId,plan.runId);assert.equal((await ui.handshake(plan.runId)).desktopMode,'open-with');assert.equal(await association(),initial);assert.deepEqual(await launches(log),[]);part.proof={privateBus:true,personalConfigAbsent:true,associationSha256:sha256(Buffer.from(initial)),handlers:['generated-success.desktop','generated-failure.desktop']};part.verification='INDEPENDENT_MATCH'})
  await recordPart(result,'checked-cancel',async part=>{result.phase='ui';await open(ui,raw);await pick(ui,true);assert.ok(!await checked(ui));await toggle(ui);await button(ui,'Cancel');await ui.idle();result.phase='verification';assert.equal(await association(),initial);assert.deepEqual(await launches(log),[]);part.ui='ACKNOWLEDGED';part.verification='INDEPENDENT_MATCH'})
  await recordPart(result,'unchecked-spaced-launch',async part=>{result.phase='ui';await open(ui,raw);await pick(ui,true);assert.ok(!await checked(ui));await button(ui,'Open');part.feedback=await ui.expectedToast(/^Opening spaced # name.txt…$/);result.phase='verification';part.launch=await verifyLaunch(1);assert.equal(await association(),initial);part.ui='ACKNOWLEDGED';part.verification='INDEPENDENT_MATCH'})
  await recordPart(result,'failed-launch',async part=>{result.phase='ui';await open(ui,raw);await pick(ui,false);assert.ok(!await checked(ui));await button(ui,'Open');const error=await ui.browser.$('.open-with-modal .pill.error');await error.waitForDisplayed({timeout:30_000});part.feedback=await error.getText();assert.match(part.feedback,/Selected application is unavailable|Failed to launch/i);assert.ok(await(await ui.browser.$('.open-with-modal')).isDisplayed());await button(ui,'Cancel');await ui.idle();result.phase='verification';assert.equal((await launches(log)).length,1);assert.equal(await association(),initial);part.ui='ACKNOWLEDGED';part.verification='INDEPENDENT_MATCH'})
  let saved
  await recordPart(result,'checked-default-launch',async part=>{result.phase='ui';await open(ui,raw);await pick(ui,true);await toggle(ui);await button(ui,'Open');part.feedback=await ui.expectedToast(/^Opening spaced # name.txt… Generated successful handler is now the default for text\/plain$/);result.phase='verification';part.launch=await verifyLaunch(2);saved=await association();assert.notEqual(saved,initial);assert.match(saved,/\[Default Applications\]\ntext\/plain=generated-success\.desktop(?:;|\n)/);part.associationSha256=sha256(Buffer.from(saved));part.ui='ACKNOWLEDGED';part.verification='INDEPENDENT_MATCH'})
  await recordPart(result,'default-cancel-preserves-association',async part=>{result.phase='ui';await open(ui,raw);await pick(ui,false);assert.ok(!await checked(ui));await button(ui,'Cancel');await ui.idle();result.phase='verification';assert.equal(await association(),saved);assert.equal((await launches(log)).length,2);part.ui='ACKNOWLEDGED';part.verification='INDEPENDENT_MATCH'})
  result.phase='verification';result.preserved=await verifyByteTree(fixture,base,new Map([[raw.split('/').at(-1),payload]]));result.resources=await releasedResources(ui,plan.runId)
 },{id:'desktop-open-with',providers:['local']})
}
