const ICON_PATHS = [
  'icons/scalable/browsey/shortcut.svg',
  'icons/scalable/browsey/download_folder.svg',
  'icons/scalable/browsey/document_folder.svg',
  'icons/scalable/browsey/pictures_folder.svg',
  'icons/scalable/browsey/video_folder.svg',
  'icons/scalable/browsey/music_folder.svg',
  'icons/scalable/browsey/templates_folder.svg',
  'icons/scalable/browsey/public_folder.svg',
  'icons/scalable/browsey/desktop_folder.svg',
  'icons/scalable/browsey/home.svg',
  'icons/scalable/browsey/folder.svg',
  'icons/scalable/browsey/compressed.svg',
  'icons/scalable/browsey/file.svg',
  'icons/scalable/browsey/textfile.svg',
  'icons/scalable/browsey/picture_file.svg',
  'icons/scalable/browsey/video_file.svg',
  'icons/scalable/browsey/pdf_file.svg',
  'icons/scalable/browsey/spreadsheet_file.svg',
  'icons/scalable/browsey/presentation_file.svg',
  'icons/scalable/browsey/audio_file.svg',
  'icons/scalable/browsey/executable_file.svg',
  'icons/scalable/browsey/cloud.svg',
  'icons/scalable/browsey/model_3d_file.svg',
  'icons/scalable/browsey/network_folder.svg',
  'icons/scalable/browsey/document_file.svg',
  'icons/scalable/browsey/code_file.svg',
  'icons/scalable/browsey/package_file.svg',
  'icons/scalable/browsey/disk_image_file.svg',
  'icons/scalable/browsey/font_file.svg',
  'icons/scalable/browsey/ebook_file.svg',
] as const

export const iconPath = (id: number | undefined) => ICON_PATHS[id ?? 0] ?? ICON_PATHS[0]
