import { useExplorerDragDrop } from '../file-ops'
import { useExplorerInputHandlers } from '../hooks/useExplorerInputHandlers'

type ExplorerInputHandlerDeps = Parameters<typeof useExplorerInputHandlers>[0]
type ExplorerDragDropDeps = Parameters<typeof useExplorerDragDrop>[0]

export const createExplorerInputHandlersDeps = (deps: ExplorerInputHandlerDeps): ExplorerInputHandlerDeps => ({
  getViewMode: deps.getViewMode,
  getMode: deps.getMode,
  setPathInput: deps.setPathInput,
  getPathInput: deps.getPathInput,
  isInputFocused: deps.isInputFocused,
  getCurrentPath: deps.getCurrentPath,
  isSearchSessionEnabled: deps.isSearchSessionEnabled,
  getRowsEl: deps.getRowsEl,
  getHeaderEl: deps.getHeaderEl,
  getFilteredEntries: deps.getFilteredEntries,
  getSelected: deps.getSelected,
  setSelected: deps.setSelected,
  getAnchorIndex: deps.getAnchorIndex,
  setAnchorIndex: deps.setAnchorIndex,
  getCaretIndex: deps.getCaretIndex,
  setCaretIndex: deps.setCaretIndex,
  getRowHeight: deps.getRowHeight,
  getDoubleClickMs: deps.getDoubleClickMs,
  setCopyModifierActive: deps.setCopyModifierActive,
  isEditableTarget: deps.isEditableTarget,
  hasAppShortcut: deps.hasAppShortcut,
  handleGlobalKeydown: deps.handleGlobalKeydown,
  transitionToAddressMode: deps.transitionToAddressMode,
  blurPathInput: deps.blurPathInput,
  ensureGridVisible: deps.ensureGridVisible,
  getRowsKeydownHandler: deps.getRowsKeydownHandler,
  getRowSelectionHandler: deps.getRowSelectionHandler,
  selectionBox: deps.selectionBox,
  getGridCols: deps.getGridCols,
  getGridCardWidth: deps.getGridCardWidth,
  getGridRowHeight: deps.getGridRowHeight,
  getGridGap: deps.getGridGap,
  handleRowsScroll: deps.handleRowsScroll,
  handleGridScroll: deps.handleGridScroll,
  handleRowsClick: deps.handleRowsClick,
  currentView: deps.currentView,
  loadDir: deps.loadDir,
  openPartition: deps.openPartition,
  canExtractPaths: deps.canExtractPaths,
  extractEntries: deps.extractEntries,
  open: deps.open,
  isBlockingModalOpen: deps.isBlockingModalOpen,
  isDeleteModalOpen: deps.isDeleteModalOpen,
  closeDeleteModal: deps.closeDeleteModal,
  isRenameModalOpen: deps.isRenameModalOpen,
  closeRenameModal: deps.closeRenameModal,
  isOpenWithModalOpen: deps.isOpenWithModalOpen,
  closeOpenWithModal: deps.closeOpenWithModal,
  isPropertiesModalOpen: deps.isPropertiesModalOpen,
  closePropertiesModal: deps.closePropertiesModal,
  isCompressModalOpen: deps.isCompressModalOpen,
  closeCompressModal: deps.closeCompressModal,
  isCheckDuplicatesModalOpen: deps.isCheckDuplicatesModalOpen,
  closeCheckDuplicatesModal: deps.closeCheckDuplicatesModal,
  isNewFolderModalOpen: deps.isNewFolderModalOpen,
  closeNewFolderModal: deps.closeNewFolderModal,
  isNewFileModalOpen: deps.isNewFileModalOpen,
  closeNewFileModal: deps.closeNewFileModal,
  isBookmarkModalOpen: deps.isBookmarkModalOpen,
  closeBookmarkModal: deps.closeBookmarkModal,
  isContextMenuOpen: deps.isContextMenuOpen,
  closeContextMenu: deps.closeContextMenu,
  isBlankMenuOpen: deps.isBlankMenuOpen,
  closeBlankContextMenu: deps.closeBlankContextMenu,
  suppressHoverMs: deps.suppressHoverMs,
})

export const createExplorerDragDropDeps = (deps: ExplorerDragDropDeps): ExplorerDragDropDeps => ({
  currentView: deps.currentView,
  currentPath: deps.currentPath,
  getSelectedSet: deps.getSelectedSet,
  loadDir: deps.loadDir,
  focusEntryInCurrentList: deps.focusEntryInCurrentList,
  handlePasteOrMove: deps.handlePasteOrMove,
  showToast: deps.showToast,
})
